/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	RCC_AHB1ENR_t *rcc_ENR = (RCC_AHB1ENR_t*)0x40023830;
	GPIOx_MODE_t *gpioDMode= (GPIOx_MODE_t*)0x40020C00;
	GPIOx_ODR_t *gpioDODR= (GPIOx_ODR_t*)0x40020C14;

	rcc_ENR->gpiod_en = 1;
		//*pGpioDModeReg &= 0xFCFFFFFF;
	gpioDMode->pin_12 =1;


	while(1){
		gpioDODR->pin_12 = 1;
		for(uint32_t i=0;i<300000;i++);
		gpioDODR->pin_12 = 0;
		for(uint32_t i=0;i<300000;i++);

	}

}
