/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
int  divfunc(int a,int b)
{
	return a/b;

}
int main(void)
{
    /* Loop forever */
	//Create an Divide by zzero trap to enable divide by zzero fault which will invoke usage fault
	// in SCB there is an CCR register 32 bit , enable the 4th bit for DIV_ZERO_TRAP
	//1. enable the faults handler using SCHSR rgister
			// SCHSR is part of SCB
			// this register is used to enable the system handlers
	uint32_t * pSHCSR = (uint32_t*) 0xE000ED24;
    uint32_t* pCCR=(uint32_t*)0xE000ED14;
	*pSHCSR |=(1<<18); //usageFault
	*pSHCSR |=(1<<17); //Bus fault
	*pSHCSR |=(1<<16); // Mem fault



	//set the 4th bit for DIV_zero-trap
	*pCCR |=(1<<4);

	divfunc(5,0);

	for(;;);
}
void HardFault_Handler(){
	printf("[HardFault handler]");
	while(1);
}
void MemManage_Handler(){
	printf("[memory fault  handler]");
	while(1);
}
void BusFault_Handler(){
	printf("[Bus fault  handler]");
	while(1);
}
void UsageFault_Handler(){
	printf("[Usage Fault handler]");
	while(1);
}
