/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */


	//now we have to program the Interrupt for IRQ39
	uint32_t *nvicSetPendingReg = (uint32_t*)0xE000E204;
	uint32_t *nvicSetEnableReg=(uint32_t*)0xE000E104;
	printf("In the thread Mode - check the xpsr register\n");
	*nvicSetPendingReg |=(1<<(39%32));

	*nvicSetEnableReg |=(1<<(39%32));


	for(;;);
}

void USART3_IRQHandler(void){
	printf("In Handler mode\n");
	printf("In USART3 ISR\n");

}
