/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#define alias_base 0x22000000
#define bit_band_mem 0x20000200
#define bit_band_base 0x20000000

int main(void)
{
    /* Loop forever */

	// we have to chnage the 7th bit of the memory location 0x20000200 using its alias addres
	// the above location points to memory map of SRAM
	// in SRAM and peripheral region only first 1MB can be aliased

  // go to memory browser and check this
	uint32_t* alias_addr=(uint32_t*)(alias_base +(32 * (bit_band_mem-bit_band_base))+7*4);

	*alias_addr=1;

	for(;;);
}
