/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#define IRQNO_TIMER2 28
#define IRQNO_I2C1 31


uint32_t *nvicSetPendingReg = (uint32_t*)0xE000E200;
uint32_t *nvicSetEnableReg=(uint32_t*)0xE000E100;
uint32_t *nvicInterruptPriorityReg=(uint32_t*)0xE000E400;


void configure_priority_for_irqs(uint8_t irq_no,uint8_t priority_value){

	// first find the IPRx
	// than find position in IPRx
    // understanfd the logic for this on paper
    // there are 60 registers each of 32 bits
	// each register is divided into 4 parts of 8 bits each .. for every IRQ
	// we have to configure the priority in that 8 bits
	uint8_t iprx = irq_no/4;
	uint32_t *ipr =(uint32_t*)(nvicInterruptPriorityReg+iprx);

	uint8_t pos = (irq_no %4) *8;

	*ipr &= ~(0xFF << pos); // clear the bits
	*ipr |= (priority_value << pos);
}

int main(void)
{
    /* Loop forever */
	//question ; Generate an TIM2 global interrupt and I2c1 event interrupt using NVIC interrupt pending register and observr the execution of ISR
	// also note when ISR have same priority
	// 1. configure the Prioriity for peripherals

	configure_priority_for_irqs(IRQNO_TIMER2,0x80);
	configure_priority_for_irqs(IRQNO_I2C1,0x20); // lowerr number ==> higher prioirty

	//set pending Reg for timer 2
	*nvicSetPendingReg |=(1<<IRQNO_TIMER2);


	//set the enable IRQ Register ... so that IRQ can be sent to the processor
	*nvicSetEnableReg |=(1<<IRQNO_I2C1);
	*nvicSetEnableReg |=(1<<IRQNO_TIMER2);


	for(;;);
}

void TIM2_IRQHandler(void){
  printf("TIm2 IRQ handler\n");
  *nvicSetPendingReg |=(1<<IRQNO_I2C1);
  while(1); // added this line to check if the Interrupt will be preempted ;

}
void I2C1_EV_IRQHandler(void){
	printf("I2C1 IRQ handler\n");

}
