/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
void svcOperation(int a,int b)
{
	// a and b will fetch the value from the register
    // 37 service number for add , 38 for mult
	uint32_t ops;
	uint32_t result;
	__asm("SVC #37");
	__asm("MOV %0,R0":"=r"(result)::);
    __asm("MOV %0,R2":"=r"(ops)::);
	printf("The operation performed was: %ld\n",ops);
	printf("The result of the operation was:%ld\n",result);



}
int main(void)
{
    /* Loop forever */

	// Generate an SVC exception and in the Handler perform the Math Operation
	// return the result again in Thread Mode
	printf("Main function\n");

	svcOperation(4,5); // the 4 and 5 will be copied into the register

	for(;;);
}

__attribute__((naked)) void SVC_Handler(void){
	// so that we can extract the service number and send to c handler
	// we want to extract MSP in unlatered way
	__asm("MRS r0,MSP");
	__asm("B svc_Handler_c");

}

void svc_Handler_c(uint32_t *pBaseStackFrame){
	printf("Inside the c handler for svc :\n");
	printf("The PBaseStackFrame is = %p\n",pBaseStackFrame);
	printf("The r0 is = %lx\n",pBaseStackFrame[0]);
	printf("The r1 is = %lx\n",pBaseStackFrame[1]);
	printf("The r2 is = %lx\n",pBaseStackFrame[2]);
	printf("The r3 is = %lx\n",pBaseStackFrame[3]);
	printf("The r12 is = %lx\n",pBaseStackFrame[4]);
	printf("The lr is = %lx\n",pBaseStackFrame[5]);
	printf("The pc is = %lx\n",pBaseStackFrame[6]);
	printf("The xpsr is = %lx\n",pBaseStackFrame[7]);
    uint8_t *SVCAddr = (uint8_t*)pBaseStackFrame[6];
		// we want to go to previous instruction
	SVCAddr -=2;

	if(*SVCAddr ==37 )
	{
		pBaseStackFrame[0]=pBaseStackFrame[0] + pBaseStackFrame[1];
	}
	else
	{
		pBaseStackFrame[0]=pBaseStackFrame[0] * pBaseStackFrame[1];
	}
	pBaseStackFrame[2]=*SVCAddr;



}
