/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	uint32_t *pClkCtrlReg = (uint32_t*)0x40023830;
	uint32_t *pGpioDModeReg= (uint32_t*)0x40020C00;
	uint32_t *pGpioDOutputReg = (uint32_t*)0x40020C14;
    uint32_t *pGpioAModeReg=(uint32_t*)0x40020000;
    uint32_t *pGpioAInputReg=(uint32_t*)0x40020010;

    //enable peripheral D
	*pClkCtrlReg |= (1<<3);
	//enable peripheral A
	*pClkCtrlReg |=(1<<0);

	 // for PD12 led
	*pGpioDModeReg &=~(3<<24);
	*pGpioDModeReg |=(1<<24);
	//set GPIO A mode to input mode
	*pGpioAModeReg &=~(3<<24);

	while(1){
		uint32_t pinStatus=*(pGpioAInputReg) & 1;
		if(pinStatus){
			*pGpioDOutputReg |= (1<<12);
		}
		else
		{
			*pGpioDOutputReg &= ~(1<<12);
		}
	}

}
