/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	uint32_t *pClkCtrlReg = (uint32_t*)0x40023830;
	uint32_t *pGpioDModeReg= (uint32_t*)0x40020C00;
	uint32_t *pGpioOutputReg = (uint32_t*)0x40020C14;

	*pClkCtrlReg |= (1<<3);
		//*pGpioDModeReg &= 0xFCFFFFFF;
	*pGpioDModeReg &=~(3<<24);
	*pGpioDModeReg |=(1<<24);

	while(1){
		*pGpioOutputReg |= (1<<12);
		for(uint32_t i=0;i<300000;i++);
		*pGpioOutputReg &= ~(1<<12);
		for(uint32_t i=0;i<300000;i++);

	}

}
