/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */

	//generate an SVC Exception
	uint32_t data;

	__asm("SVC #8");
	__asm("MOV %0,R0":"=r"(data)::);

	printf("data is = %ld\n",data);

	for(;;);
}


__attribute__((naked))void SVC_Handler(void){

	// if i try to extract the SVC number by extracting MSP here
	// i will get wrong value of MSP so use an naked function to avoid changes in MSP and get the crct value
	__asm("MRS r0,MSP"); // copy the unaltered value of MSP into R0;
	__asm("B SVC_Handler_c"); //Branch statement to call c function


}

void SVC_Handler_c(uint32_t* pBaseStackFrame){
	printf("Printing the Stacked frame before moving to Handler\n");
	printf("The PBaseStackFrame is = %p\n",pBaseStackFrame);
	printf("The r0 is = %lx\n",pBaseStackFrame[0]);
	printf("The r1 is = %lx\n",pBaseStackFrame[1]);
	printf("The r2 is = %lx\n",pBaseStackFrame[2]);
	printf("The r3 is = %lx\n",pBaseStackFrame[3]);
	printf("The r12 is = %lx\n",pBaseStackFrame[4]);
	printf("The lr is = %lx\n",pBaseStackFrame[5]);
	printf("The pc is = %lx\n",pBaseStackFrame[6]);
	printf("The xpsr is = %lx\n",pBaseStackFrame[7]);


	uint8_t *SVCAddr = (uint8_t*)pBaseStackFrame[6];
	// we want to go to previous instruction
	SVCAddr -=2;

	printf("%d\n",*SVCAddr); // since it points to 1 byte prints 08

	pBaseStackFrame[0]=*SVCAddr+5;


}
