/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	uint32_t *RccAhb1Enr= (uint32_t*) 0x40023830;
	uint32_t *GpioDModerReg= (uint32_t*) 0x40020C00;
	uint32_t *GpioDOutputDReg= (uint32_t*) 0x40020C14;

	//first enable the peripheral using clock register ;
	*RccAhb1Enr |=(1<<3);

	//set the moder register as output
	*GpioDModerReg |=(0x55<<24);
	//set bit 1 in output data register

	// paralled LED to be blinking alternatively , LD4 and LD5
	while(1)
	{
		*GpioDOutputDReg &=(0 << 12);
		*GpioDOutputDReg |=(1 << 12);
		for(int i=0;i<300000;i++);
		*GpioDOutputDReg &=(0 << 12);
		*GpioDOutputDReg |=(4<<12);
		for(int i=0;i<300000;i++);
	}






	for(;;);
}
