/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	//enable the usage fault handler , mem fault handler , bus fault handler

	 /* Loop forever */
		// configure the faults and see the flow
		// Generate an usage fault using invalid instruction
		// Generate an Undefined instruction in SRAM region

		//1. enable the faults handler using SCHSR rgister
		// SCHSR is part of SCB
		// this register is used to enable the system handlers
		uint32_t * pSHCSR = (uint32_t*) 0xE000ED24;

		*pSHCSR |=(1<<18); //usageFault
		*pSHCSR |=(1<<17); //Bus fault
		*pSHCSR |=(1<<16); // Mem fault


		//create an function pointer to execute an code in SRAM region
		uint32_t * pSRAM=(uint32_t*)0x20001000; // a region in SRAM where our instruction to be execute will reside
		*pSRAM=0xFFFFFFFF; // actually an invalid op-code

		void (*fptr)(void) = (void *)0x20001000;
		// the function address pointer should have a value whose LSB is 1 for THUMB ISA
		// here LSB is 0 -- > indicating ARM ISA
		// should generate an usage fault for invalid instruction
		fptr();



	    for(;;);
}

void HardFault_Handler(){
	printf("[HardFault handler]");
	while(1);
}
void MemManage_Handler(){
	printf("[memory fault  handler]");
	while(1);
}
void BusFault_Handler(){
	printf("[Bus fault  handler]");
	while(1);
}
void UsageFault_Handler(){
	printf("[Usage Fault handler]");
	while(1);
}
