/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	// configure the faults and see the flow
	// Generate an usage fault using invalid instruction
	// Generate an Undefined instruction in SRAM region

	//1. enable the faults handler using SCHSR rgister
	// SCHSR is part of SCB
	// this register is used to enable the system handlers
	uint32_t * pSHCSR = (uint32_t*) 0xE000ED24;

	*pSHCSR |=(1<<18); //usageFault
	*pSHCSR |=(1<<17); //Bus fault
	*pSHCSR |=(1<<16); // Mem fault

	//2. implement the fault handler --done
	//3. generate the fault

	uint32_t* pSRAM=(uint32_t*)0x20001000;
	*pSRAM=0xFFFFFFFF;
	void (*fptr)(void) = (void*)0x20001001; // declared an function pointer
	 // an address in RAM
	 // this is an invalid op-code types
	// Note SRAM is not XN
	fptr(); // this will try to execute the instructions at 0x20001000 which is an invalid op-code
	// should generate an usageFault exceptions
	//4. see using fault analyzer


	for(;;);
}

void HardFault_Handler(){
	printf("[HardFault handler]");
	while(1);
}
void MemManage_Handler(){
	printf("[memory fault  handler]");
	while(1);
}
void BusFault_Handler(){
	printf("[Bus fault  handler]");
	while(1);
}
void UsageFault_Handler(){
	printf("[Usage Fault handler]");
	while(1);
}
